<?php

namespace Tests\Feature;

use App\Services\TodolstService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class TodolistServiceTest extends TestCase
{
    private TodolstService $todolstService;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->todolstService = $this->app->make(TodolstService::class);
    }

    public function testTodolistNotNull()
    {
        self::assertNotNull($this->todolstService);
    }
}
