<?php

namespace Tests\Feature;

use App\Services\UserServices;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;
use function PHPUnit\Framework\assertFalse;
use function PHPUnit\Framework\assertTrue;

class UserServiceTest extends TestCase
{
    private UserServices $userServices;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->userServices = $this->app->make(UserServices::class);
    }

    public function testLoginSuccess()
    {
        assertTrue($this->userServices->login('ade', "rahasia"));
    }

    public function testLoginNotFound()
    {
        assertFalse($this->userServices->login('nafil', "ade"));
    }

    public function testLoginWrongPassword()
    {
        assertFalse($this->userServices->login('ade', "salah"));
    }
}
